const globalGateData = {
  "status": "success",
  "data": [
    {
      "subdivision_id": 4777,
      "subdivision_code": "VX",
      "subdivision_name": "Vịnh Xanh",
      "apartment_data": [
        {
          "product_code": "BM34-73",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 119.16,
          "coordinate_y": -109.02,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM25-54",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 121.82265403177168,
          "coordinate_y": -112.96561297541709,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM25-07",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 117.1875,
          "coordinate_y": -125.203125,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM60-23",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 128.984375,
          "coordinate_y": -136.171875,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM79-11",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 79.9765625,
          "coordinate_y": -157.8515625,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM87-06",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 55.28125,
          "coordinate_y": -171.5234375,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM87-10",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 56.1953125,
          "coordinate_y": -173.0078125,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM73-38",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 98.453125,
          "coordinate_y": -159.4921875,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM69-19",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 111.8359375,
          "coordinate_y": -157.3125,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        },
        {
          "product_code": "BM65-08",
          "state_line": "available",
          "apartment_price": 0,
          "land_area": 0,
          "construction_area": 0,
          "type_name": "",
          "direction": "",
          "image_url": "",
          "marker_shape": "pin",
          "marker_color": "default",
          "coordinate_x": 125.21875,
          "coordinate_y": -139.3984375,
          "subdivision_id": 4777,
          "project_id": 355,
          "fund_groups_sell_code": "QA"
        }
      ]
    }
  ]
};