const vinhXanhData = {
  "code": 1,
  "error": false,
  "data": [
    {
      "fund_groups_sell_code": "ALL",
      "fund_groups_sell_name": "Tất cả",
      "apartment_data": [
        {
          "apartment_price": 53421849985,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 243775,
          "product_code": "VX1-02",
          "product_name": "VX1-02",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 63.17,
          "coordinate_y": -103.25,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20984322098,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245862,
          "product_code": "VX1-05",
          "product_name": "VX1-05",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.55,
          "coordinate_y": -101.47,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20914285259,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164800,
          "product_code": "VX1-07",
          "product_name": "VX1-07",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.47,
          "coordinate_y": -101.87,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19023290420,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164730,
          "product_code": "VX1-15",
          "product_name": "VX1-15",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.15,
          "coordinate_y": -103.41,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19443910405,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244697,
          "product_code": "VX1-25",
          "product_name": "VX1-25",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.7,
          "coordinate_y": -105.36,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19584117066,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244698,
          "product_code": "VX1-27",
          "product_name": "VX1-27",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.63,
          "coordinate_y": -105.72,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 50782170202,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247645,
          "product_code": "VX1-29",
          "product_name": "VX1-29",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.52,
          "coordinate_y": -106.23,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 51936700717,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247644,
          "product_code": "VX1-31",
          "product_name": "VX1-31",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.14,
          "coordinate_y": -107.93,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 50452685125,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248881,
          "product_code": "VX1-36",
          "product_name": "VX1-36",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.52,
          "coordinate_y": -115.28,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 50452685125,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245390,
          "product_code": "VX1-38",
          "product_name": "VX1-38",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.39,
          "coordinate_y": -115.98,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 50452685125,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245391,
          "product_code": "VX1-40",
          "product_name": "VX1-40",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.26,
          "coordinate_y": -116.56,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 54112988410,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245389,
          "product_code": "VX1-44",
          "product_name": "VX1-44",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.96,
          "coordinate_y": -117.89,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19093327260,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244146,
          "product_code": "VX1-49",
          "product_name": "VX1-49",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.29,
          "coordinate_y": -111.59,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19163364099,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248887,
          "product_code": "VX1-69",
          "product_name": "VX1-69",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.4,
          "coordinate_y": -115.39,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 19163364099,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 165485,
          "product_code": "VX1-71",
          "product_name": "VX1-71",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.29,
          "coordinate_y": -115.81,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 49409135375,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244149,
          "product_code": "VX2-01",
          "product_name": "VX2-01",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.5,
          "coordinate_y": -96.57,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 43765730793,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244060,
          "product_code": "VX2-03",
          "product_name": "VX2-03",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.99,
          "coordinate_y": -97.13,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 51289446340,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244063,
          "product_code": "VX2-04",
          "product_name": "VX2-04",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.35,
          "coordinate_y": -94.71,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 18841036730,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248877,
          "product_code": "VX2-05",
          "product_name": "VX2-05",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.89,
          "coordinate_y": -97.55,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 52053710386,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244061,
          "product_code": "VX2-06",
          "product_name": "VX2-06",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.71,
          "coordinate_y": -95.6,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20633319989,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248893,
          "product_code": "VX2-24",
          "product_name": "VX2-24",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.97,
          "coordinate_y": -101.64,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14694243847,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244045,
          "product_code": "VX2-29",
          "product_name": "VX2-29",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.08,
          "coordinate_y": -101.07,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 21113853183,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244136,
          "product_code": "VX2-38",
          "product_name": "VX2-38",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.28,
          "coordinate_y": -104.68,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15366511429,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164745,
          "product_code": "VX2-47",
          "product_name": "VX2-47",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.49,
          "coordinate_y": -103.77,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20633319989,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164798,
          "product_code": "VX2-50",
          "product_name": "VX2-50",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.32,
          "coordinate_y": -108.89,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15098622946,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244049,
          "product_code": "VX2-63",
          "product_name": "VX2-63",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.44,
          "coordinate_y": -108.12,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14809823098,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164738,
          "product_code": "VX2-67",
          "product_name": "VX2-67",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.31,
          "coordinate_y": -108.69,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14960921739,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164818,
          "product_code": "VX2-71",
          "product_name": "VX2-71",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.19,
          "coordinate_y": -109.26,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20693960212,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 243780,
          "product_code": "VX2-73",
          "product_name": "VX2-73",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.11,
          "coordinate_y": -109.57,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20693960212,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164775,
          "product_code": "VX2-75",
          "product_name": "VX2-75",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.97,
          "coordinate_y": -110.09,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 17787143765,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164766,
          "product_code": "VX2-87",
          "product_name": "VX2-87",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.53,
          "coordinate_y": -111.74,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14845342488,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244700,
          "product_code": "VX2-91",
          "product_name": "VX2-91",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.36,
          "coordinate_y": -112.5,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 53458602308,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247731,
          "product_code": "VX3-02",
          "product_name": "VX3-02",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.35,
          "coordinate_y": -84.96,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 45043926788,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164758,
          "product_code": "VX3-03",
          "product_name": "VX3-03",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.47,
          "coordinate_y": -87.88,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 17800256776,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164814,
          "product_code": "VX3-109",
          "product_name": "VX3-109",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 57.59,
          "coordinate_y": -108.71,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14578420923,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244212,
          "product_code": "VX3-119",
          "product_name": "VX3-119",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 57.19,
          "coordinate_y": -110.3,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 17800256776,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244214,
          "product_code": "VX3-133",
          "product_name": "VX3-133",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 56.63,
          "coordinate_y": -112.48,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 47904012648,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 165481,
          "product_code": "VX3-14",
          "product_name": "VX3-14",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 63.11,
          "coordinate_y": -89.62,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 55961043635,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248597,
          "product_code": "VX3-155",
          "product_name": "VX3-155",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.75,
          "coordinate_y": -115.87,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 49290966568,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244062,
          "product_code": "VX3-18",
          "product_name": "VX3-18",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.79,
          "coordinate_y": -91.03,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 51202601320,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244139,
          "product_code": "VX3-24",
          "product_name": "VX3-24",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.34,
          "coordinate_y": -93.16,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 29840607938,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164808,
          "product_code": "VX3-26",
          "product_name": "VX3-26",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.39,
          "coordinate_y": -97.16,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20953745596,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244695,
          "product_code": "VX3-28",
          "product_name": "VX3-28",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.27,
          "coordinate_y": -97.62,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 47164821044,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 249759,
          "product_code": "VX3-35",
          "product_name": "VX3-35",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.7,
          "coordinate_y": -95.81,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20473235785,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244144,
          "product_code": "VX3-38",
          "product_name": "VX3-38",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.79,
          "coordinate_y": -99.82,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15019076757,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164772,
          "product_code": "VX3-45",
          "product_name": "VX3-45",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.32,
          "coordinate_y": -97.37,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14636088829,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244215,
          "product_code": "VX3-53",
          "product_name": "VX3-53",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.03,
          "coordinate_y": -98.71,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 29840607938,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 165497,
          "product_code": "VX3-56",
          "product_name": "VX3-56",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.82,
          "coordinate_y": -103.85,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 49462410155,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244142,
          "product_code": "VX3-58",
          "product_name": "VX3-58",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.69,
          "coordinate_y": -104.48,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20713362093,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247729,
          "product_code": "VX3-66",
          "product_name": "VX3-66",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.96,
          "coordinate_y": -107.63,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20232719786,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248902,
          "product_code": "VX3-78",
          "product_name": "VX3-78",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.31,
          "coordinate_y": -110.23,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 46467762362,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244143,
          "product_code": "VX3-87",
          "product_name": "VX3-87",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.41,
          "coordinate_y": -105.42,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 38676912540,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 249764,
          "product_code": "VX4-01",
          "product_name": "VX4-01",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.59,
          "coordinate_y": -77.75,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 42736957878,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247730,
          "product_code": "VX4-03",
          "product_name": "VX4-03",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 63.02,
          "coordinate_y": -78.23,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14960921739,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164715,
          "product_code": "VX4-101",
          "product_name": "VX4-101",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.51,
          "coordinate_y": -98.02,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14809823098,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164756,
          "product_code": "VX4-103",
          "product_name": "VX4-103",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.44,
          "coordinate_y": -98.29,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 18841036730,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248878,
          "product_code": "VX4-127",
          "product_name": "VX4-127",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 57.55,
          "coordinate_y": -101.9,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 23547952409,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245392,
          "product_code": "VX4-134",
          "product_name": "VX4-134",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.37,
          "coordinate_y": -114.8,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 55442644091,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248598,
          "product_code": "VX4-136",
          "product_name": "VX4-136",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.19,
          "coordinate_y": -115.4,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15365020864,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247639,
          "product_code": "VX4-137",
          "product_name": "VX4-137",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 56.71,
          "coordinate_y": -105.25,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15249229603,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164764,
          "product_code": "VX4-139",
          "product_name": "VX4-139",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 56.62,
          "coordinate_y": -105.51,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14578177367,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 181337,
          "product_code": "VX4-157",
          "product_name": "VX4-157",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.91,
          "coordinate_y": -108.19,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14729276008,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 165475,
          "product_code": "VX4-159",
          "product_name": "VX4-159",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.84,
          "coordinate_y": -108.49,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14578177367,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164812,
          "product_code": "VX4-167",
          "product_name": "VX4-167",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.55,
          "coordinate_y": -109.63,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14578177367,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164760,
          "product_code": "VX4-173",
          "product_name": "VX4-173",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 55.34,
          "coordinate_y": -110.42,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14845098931,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247640,
          "product_code": "VX4-181",
          "product_name": "VX4-181",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 54.98,
          "coordinate_y": -111.74,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14845098931,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247641,
          "product_code": "VX4-183",
          "product_name": "VX4-183",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 54.91,
          "coordinate_y": -112.03,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 18852363012,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248879,
          "product_code": "VX4-195",
          "product_name": "VX4-195",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 54.45,
          "coordinate_y": -113.66,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20556286294,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164748,
          "product_code": "VX4-30",
          "product_name": "VX4-30",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.79,
          "coordinate_y": -88.41,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20553667576,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 249756,
          "product_code": "VX4-32",
          "product_name": "VX4-32",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.68,
          "coordinate_y": -88.9,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20553667576,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 245393,
          "product_code": "VX4-34",
          "product_name": "VX4-34",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 61.6,
          "coordinate_y": -89.37,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 54819233647,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 247642,
          "product_code": "VX4-52",
          "product_name": "VX4-52",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.65,
          "coordinate_y": -93.48,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 49779876846,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248882,
          "product_code": "VX4-54",
          "product_name": "VX4-54",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 60.2,
          "coordinate_y": -95.31,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 47539574181,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244046,
          "product_code": "VX4-79",
          "product_name": "VX4-79",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.37,
          "coordinate_y": -94.52,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15482317301,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244693,
          "product_code": "VX4-83",
          "product_name": "VX4-83",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.16,
          "coordinate_y": -95.32,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 15366511429,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244694,
          "product_code": "VX4-85",
          "product_name": "VX4-85",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.1,
          "coordinate_y": -95.57,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 14809823098,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 164717,
          "product_code": "VX4-97",
          "product_name": "VX4-97",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.64,
          "coordinate_y": -97.47,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 25329941238,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 248883,
          "product_code": "VX5-02",
          "product_name": "VX5-02",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 62.45,
          "coordinate_y": -78.32,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 21273656996,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 250449,
          "product_code": "VX5-140",
          "product_name": "VX5-140",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 54.17,
          "coordinate_y": -112.14,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 21432961822,
          "price_description": "Giá Full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 250450,
          "product_code": "VX5-142",
          "product_name": "VX5-142",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 54.04,
          "coordinate_y": -112.59,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 20876298829,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244057,
          "product_code": "VX5-56",
          "product_name": "VX5-56",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.71,
          "coordinate_y": -90.34,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 26826483042,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244059,
          "product_code": "VX5-62",
          "product_name": "VX5-62",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 59.41,
          "coordinate_y": -91.64,
          "fund_groups_sell_code": "QA"
        },
        {
          "apartment_price": 30680733005,
          "price_description": "Giá full",
          "state_line": "available",
          "is_not_show": false,
          "is_favourite": false,
          "product_id": 244226,
          "product_code": "VX5-68",
          "product_name": "VX5-68",
          "project_id": 355,
          "subdivision_id": 4777,
          "coordinate_x": 58.71,
          "coordinate_y": -94.57,
          "fund_groups_sell_code": "QA"
        }
      ]
    }
  ]
};